/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202502SearchProductsResponseDataProductsSkusExternalListPrices } from './SearchProductsResponseDataProductsSkusExternalListPrices';
import { Product202502SearchProductsResponseDataProductsSkusInventory } from './SearchProductsResponseDataProductsSkusInventory';
import { Product202502SearchProductsResponseDataProductsSkusListPrice } from './SearchProductsResponseDataProductsSkusListPrice';
import { Product202502SearchProductsResponseDataProductsSkusPreSale } from './SearchProductsResponseDataProductsSkusPreSale';
import { Product202502SearchProductsResponseDataProductsSkusPrice } from './SearchProductsResponseDataProductsSkusPrice';

export class Product202502SearchProductsResponseDataProductsSkus {
    /**
    * The SKU list price (e.g. MSRP, RRP) or original price information on external ecommerce platforms. Applicable only for selected sellers in the US market.  **Note**: This value may appear as the strikethrough price on the product page. However, whether the strikethrough price is shown and the amount shown are subject to the audit team\'s review and decision based on various pricing information.
    */
    'externalListPrices'?: Array<Product202502SearchProductsResponseDataProductsSkusExternalListPrices>;
    /**
    * The SKU ID generated by TikTok Shop.
    */
    'id'?: string;
    /**
    * SKU inventory information.
    */
    'inventory'?: Array<Product202502SearchProductsResponseDataProductsSkusInventory>;
    'listPrice'?: Product202502SearchProductsResponseDataProductsSkusListPrice;
    'preSale'?: Product202502SearchProductsResponseDataProductsSkusPreSale;
    'price'?: Product202502SearchProductsResponseDataProductsSkusPrice;
    /**
    * An internal code/name for managing SKUs, not visible to buyers. 
    */
    'sellerSku'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalListPrices",
            "baseName": "external_list_prices",
            "type": "Array<Product202502SearchProductsResponseDataProductsSkusExternalListPrices>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202502SearchProductsResponseDataProductsSkusInventory>"
        },
        {
            "name": "listPrice",
            "baseName": "list_price",
            "type": "Product202502SearchProductsResponseDataProductsSkusListPrice"
        },
        {
            "name": "preSale",
            "baseName": "pre_sale",
            "type": "Product202502SearchProductsResponseDataProductsSkusPreSale"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202502SearchProductsResponseDataProductsSkusPrice"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202502SearchProductsResponseDataProductsSkus.attributeTypeMap;
    }
}

