/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309PublishGlobalProductRequestBodyPublishTargetSkusInventory } from './PublishGlobalProductRequestBodyPublishTargetSkusInventory';
import { Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice } from './PublishGlobalProductRequestBodyPublishTargetSkusPrice';

export class Product202309PublishGlobalProductRequestBodyPublishTargetSkus {
    'inventory'?: Product202309PublishGlobalProductRequestBodyPublishTargetSkusInventory;
    'price'?: Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice;
    /**
    * The global SKU ID to be published. After publishing, a corresponding local product SKU will be created and linked to the global SKU.
    */
    'relatedGlobalSkuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Product202309PublishGlobalProductRequestBodyPublishTargetSkusInventory"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202309PublishGlobalProductRequestBodyPublishTargetSkusPrice"
        },
        {
            "name": "relatedGlobalSkuId",
            "baseName": "related_global_sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309PublishGlobalProductRequestBodyPublishTargetSkus.attributeTypeMap;
    }
}

